DROP TYPE IF EXISTS ratings CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS film_genre CASCADE;

CREATE TYPE ratings AS ENUM ('G', 'PG', 'PG-13','R', 'NC-17');

CREATE TABLE films (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(64) NOT NULL CHECK(TRIM(name) <> ''),
    description varchar(200) NOT NULL,
    release_date date NOT NULL CHECK (release_date > '1895-12-28'),
    duration int NOT NULL CHECK (duration > 0),
    rating ratings NOT NULL
);


CREATE TABLE users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(64) NOT NULL CHECK(email ~ ('^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$')) UNIQUE,
    login varchar(64) NOT NULL CHECK(TRIM(name) <> '') UNIQUE,
    name varchar(64) NULL,
    birthday date CHECK (birthday < NOW())
);

CREATE TABLE likes (
        film_id int REFERENCES films(id),
        user_id int REFERENCES users(id),
        UNIQUE(film_id, user_id)
);

CREATE TABLE friends(
    user_id int REFERENCES users(id),
    friend_id int REFERENCES users(id),
    is_confirmed boolean DEFAULT false,
    UNIQUE(user_id, friend_id)
);

CREATE TABLE genres (
    id int PRIMARY KEY,
    title varchar(32) NOT NULL UNIQUE
);

CREATE TABLE film_genre (
    film_id int REFERENCES films(id),
    genre_id int REFERENCES genres(id),
    UNIQUE (film_id, genre_id)
);